version: "3.9"
services:
  frontend:
    image: nginx:latest
    container_name: webserver
    ports:
      - 8010:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./http.js:/etc/nginx/http.js
